version: "3"

services:

  node:
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 7000:7000
    networks:
      - bc-network

networks:
  bc-network: